const desc1 = "Modern space research in India is traced to the 1920s, when scientist "
    "S. K. Mitra conducted a series of experiments leading to the sounding of the ionosphere "
    "by applying ground-based radio methods in Kolkata. Later, Indian scientists like "
    "C.V. Raman and Meghnad Saha contributed to scientific principles applicable in space sciences. "
    "However, it was the period after 1945 that saw important developments being made in coordinated space research in India. "
    "Organised space research in India was spearheaded by two scientists: Vikram Sarabhai—founder of the "
    "Physical Research Laboratory at Ahmedabad—and Homi Bhabha, who established the Tata Institute of "
    "Fundamental Research in 1945. Initial experiments in space sciences included the study of cosmic radiation, "
    "high altitude and airborne testing, deep underground experimentation at the Kolar mines—one of the deepest "
    "mining sites in the world—and studies of the upper atmosphere. Studies were carried out at research laboratories, "
    "universities, and independent locations."
    "\n"
    "\n"
    "In 1950, the Department of Atomic Energy was founded with Bhabha as its secretary. The department provided "
    "funding for space research throughout India. During this time, tests continued on aspects of meteorology and "
    "the Earth's magnetic field, a topic that was being studied in India since the establishment of the observatory at "
    "Colaba in 1823. In 1954, the Uttar Pradesh state observatory was established at the foothills of the Himalayas."
    " The Rangpur Observatory was set up in 1957 at Osmania University, Hyderabad. Space research was further encouraged "
    "by the government of India. In 1957, the Soviet Union launched Sputnik 1 and opened up possibilities for the rest of "
    "the world to conduct a space launch"
    "\n"
    "\n"
    "The Indian National Committee for Space Research (INCOSPAR) was set up in 1962 by PM Nehru on the urging of "
    "Vikram Sarabhai. There was no dedicated ministry for space program initially and all activities of INCOSPAR "
    "relating to space technology continued to function within DAE. H.G.S. Murthy was appointed as the first Director "
    "of Thumba Equatorial Rocket Launching Station. Sounding rockets from Thumba Equatorial Rocket Launching Station "
    "were fired marking the start of upper atmospheric research in India. Indigenous series of sounding rockets named "
    "Rohini was subsequently developed and started undergoing launches from 1967 onwards.";

const desc2 = "Since the launch of Aryabhata in 1975, a number of satellite series and constellations have been "
    "deployed by Indian and foreign launchers. At present, ISRO operates one of the largest constellations of active "
    "communication and earth imaging satellites for military and civilian uses."
    "\n"
    "\n"
    "The IRS series"
    "\n"
    "The Indian Remote Sensing satellites (IRS) are the series of India's earth observation satellites. "
    "The IRS series provides remote sensing services and is the largest collection of remote sensing satellites for "
    "civilian use in operation today in the world. All the satellites are placed in polar Sun-synchronous orbit "
    "(except GISATs) and provide data in a variety of spatial, spectral and temporal resolutions to enable several "
    "programmes to be undertaken relevant to national development. The initial versions are composed of the 1 (A, B, C, D)"
    " nomenclature while the later versions were divided into sub-classes named based on their functioning and uses "
    "including Oceansat, Cartosat, HySIS, EMISAT and ResourceSat etc.. The names although again were unified into prefix "
    "EOS again regardless of functioning again in 2020. These satellites hold a wide range of applications including "
    "optical, radar and electronic reconnaissance for Indian agencies, city planning, oceanography and environmental studies."
    "\n"
    "\n"
    "The INSAT series"
    "\n"
    "The Indian National Satellite System (INSAT) are the family of communication satellites of India. "
    "It is a series of multipurpose geostationary satellites built and launched by ISRO to satisfy the telecommunications,"
    " broadcasting, meteorology and search-and-rescue needs of the country. Since the introduction of first satellite in"
    " 1983, INSAT has become the largest domestic communication system in the Asia-Pacific Region. It is a joint venture"
    " of the Department of Space, Department of Telecommunications, India Meteorological Department, "
    "All India Radio and Doordarshan. The overall coordination and management of INSAT system rests with the "
    "Secretary-level INSAT Coordination Committee. The nomenclature of satellite series was shifted to "
    "GSAT from INSAT which was further changed to CMS from 2020 onwards. These satellites have been in use by "
    "Indian Armed Forcesas well. GSAT-9 or SAARC Satellite is a notable example for serving communication services "
    "for India's smaller neighbors."
    "\n"
    "\n"
    "NavIC"
    "\n"
    "IRNSS with an operational name NavIC is an independent regional navigation satellite system developed by India. "
    "It is designed to provide accurate position information service to users in India as well as the region extending "
    "up to 1500 km from its borders, which is its primary service area. IRNSS provides two types of services, namely, "
    "Standard Positioning Service (SPS) and Restricted Service (RS) and provides a position accuracy of better than "
    "20 m in the primary service area. It is an autonomous regional satellite navigation system developed by "
    "Indian Space Research Organisation, which is under total control of Indian government. The requirement of such "
    "a navigation system is driven by the fact that access to global navigation systems like GPS is not guaranteed in "
    "hostile situations."
    "\n"
    "\n"
    "Other satellites"
    "\n"
    "Kalpana-1 (MetSat-1) was ISRO's first dedicated meteorological satellite. Indo-French satellite SARAL on "
    "25 February 2013. SARAL (or Satellite with ARgos and AltiKa) is a cooperative altimetry technology mission, "
    "used for monitoring the oceans' surface and sea levels. AltiKa measures ocean surface topography with an "
    "accuracy of 8 mm, against 2.5 cm on average using altimeters, and with a spatial resolution of 2 km.";

const desc3 = "Satellite Launch Vehicle"
    "\n"
    "Satellite Launch Vehicle (known as SLV-3) was the first space rocket to be developed by India. "
    "The initial launch in 1979 was a failure followed by a successful launch in 1980 making way for "
    "India into the club of countries with orbital launch capabilities. The development of bigger rockets "
    "was pushed ahead thereafter."
    "\n"
    "\n"
    "Augmented Satellite Launch Vehicle"
    "\n"
    "Augmented or Advanced Satellite Launch Vehicle (ASLV) was another small launch vehicle realised in 1980s to "
    "develop technologies required to place satellites into geostationary orbit. ISRO did not have adequate funds "
    "to develop ASLV and PSLV at once. Since ASLV suffered repeated failures, it was dropped in favour of a new project."
    "\n"
    "\n"
    "Polar Satellite Launch Vehicle"
    "\n"
    "Polar Satellite Launch Vehicle or PSLV is the first medium-lift launch vehicle from India which enabled "
    "India to launch all its remote-sensing satellites into Sun-synchronous orbit. PSLV had a failure in its "
    "maiden launch in 1993. Besides other two partial failure, PSLV has become primary workhorse for ISRO with "
    "more than 50 launches placing hundreds of Indian and foreign satellites into orbit."
    "\n"
    "\n"
    "Geosynchronous Satellite Launch Vehicle (GSLV)"
    "\n"
    "Geosynchronous Satellite Launch Vehicle was envisaged in 1990s to transfer significant payloads to "
    "geostationary orbit. ISRO initially had great problem in development of GSLV as development of CE-7.5 "
    "in India took a decade. US had blocked India from obtaining cryogenic technology from Russia which induced "
    "India to develop its own cryogenic engines."
    "\n"
    "\n"
    "GSLV Mark III"
    "\n"
    "Geosynchronous Satellite Launch Vehicle Mark III (GSLV Mk III), also known as LVM3, is the heaviest rocket in operational service with ISRO. Equipped with a more powerful cryogenic engine and boosters than GSLV, it has significantly higher playload capacity and allows India to launch all its communication satellites.";

const desc4 = "Astronaut training and other facilities"
    "\n"
    "The newly established Human Space Flight Centre (HSFC) will coordinate the IHSF campaign. ISRO will set up an "
    "astronaut training centre in Bangalore to prepare personnel for flights on board the crewed vehicle. "
    "The centre will use simulation facilities to train the selected astronauts in rescue and recovery operations "
    "and survival in zero gravity, and will undertake studies of the radiation environment of space. "
    "ISRO had to build centrifuges to prepare astronauts for the acceleration phase of the launch. Existing launch "
    "facilities in Satish Dhawan Space Centre would have to be upgraded for the Indian Human Spaceflight campaign. "
    "Human Space Flight Centre and Glavcosmos signed an agreement on 1 July 2019 for the selection, support, medical "
    "examination and space training of Indian astronauts. An ISRO Technical Liaison Unit (ITLU) was to be set up "
    "in Moscow to facilitate the development of some key technologies and establishment of special facilities which are "
    "essential to support life in space. The training of four Indian Air Force personnel was undertaken in Yuri "
    "Gagarin Cosmonaut Training Center and was completed in March 2021."
    "\n"
    "\n"
    "Crewed spacecraft"
    "\n"
    "ISRO is working towards an orbital crewed spacecraft that can operate for seven days in a low Earth orbit. "
    "The spacecraft, called Gaganyaan, will be the basis of the Indian Human Spaceflight Programme. The spacecraft "
    "is being developed to carry up to three people, and a planned upgraded version will be equipped with a rendezvous "
    "and docking capability. In its maiden crewed mission, ISRO's largely autonomous 3-tonne spacecraft will orbit "
    "the Earth at 400 km (250 mi) in altitude for up to seven days with a two-person crew on board. As of February "
    "2021, the crewed mission is planned to be launched on ISRO's GSLV Mk III in 2023."
    "\n"
    "\n"
    "Space station"
    "\n"
    "India plans to build a space station as a follow-up programme of the Gaganyaan mission. ISRO chairman K. "
    "Sivan has said that India will not join the International Space Station programme and will instead build a "
    "20 tonne space station on its own. It is expected to be placed in a low Earth orbit of a 400-kilometre (250 mi) "
    "altitude and be capable of harbouring three humans for 15–20 days. Rough time-frame is five to seven years after "
    "completion of Gaganyaan project.";

const desc5 = "There is a national balloon launching facility at Hyderabad jointly supported by TIFR and ISRO. "
    "This facility has been extensively used for carrying out research in high energy (i.e., X- and gamma-ray) "
    "astronomy, IR astronomy, middle atmospheric trace constituents including CFCs & aerosols, ionisation, electric "
    "conductivity and electric fields"
    "\n"
    "\n"
    "The flux of secondary particles and X-ray and gamma-rays of atmospheric origin produced by the interaction of "
    "the cosmic rays is very low. This low background, in the presence of which one has to detect the feeble signal "
    "from cosmic sources is a major advantage in conducting hard X-ray observations from India. The second advantage "
    "is that many bright sources like Cyg X-1, Crab Nebula, Scorpius X-1 and Galactic Centre sources are observable "
    "from Hyderabad due to their favourable declination. With these considerations, an X-ray astronomy group was formed"
    " at TIFR in 1967 and development of an instrument with an orientable X-ray telescope for hard X-ray observations "
    "was undertaken. The first balloon flight with the new instrument was made on 28 April 1968 in which observations "
    "of Scorpius X-1 were successfully carried out. In a succession of balloon flights made with this instrument between"
    " 1968 and 1974 a number of binary X-ray sources including Cyg X-1 and Her X-1, and the diffuse cosmic X-ray "
    "background were studied. Many new and astrophysically important results were obtained from these observations."
    "\n"
    "\n"
    "ISRO played a role in the discovery of three species of bacteria in the upper stratosphere at an altitude of between 20–40 km (12–25 mi). The bacteria, highly resistant to ultra-violet radiation, are not found elsewhere on Earth, leading to speculation on whether they are extraterrestrial in origin. These three bacteria can be considered to be extremophiles. The bacteria were named as Bacillus isronensis in recognition of ISRO's contribution in the balloon experiments, which led to its discovery, Bacillus aryabhata after India's celebrated ancient astronomer Aryabhata and Janibacter hoylei after the distinguished astrophysicist Fred Hoyle.";

const desc6 = "Chandrayaan-1"
    "\n"
    "Chandrayaan-1 was India's first mission to the Moon. The robotic lunar exploration mission included a lunar "
    "orbiter and an impactor called the Moon Impact Probe. ISRO launched the spacecraft using a modified version of"
    " the PSLV on 22 October 2008 from Satish Dhawan Space Centre, Sriharikota. The vehicle was inserted into lunar "
    "orbit on 8 November 2008. It carried high-resolution remote sensing equipment for visible, near infrared, "
    "and soft and hard X-ray frequencies. During its 312 days operational period (2 years planned), it surveyed "
    "the lunar surface to produce a complete map of its chemical characteristics and 3-dimensional topography. "
    "The polar regions were of special interest, as they possibly had ice deposits. The spacecraft carried 11 "
    "instruments: 5 Indian and 6 from foreign institutes and space agencies (including NASA, ESA, Bulgarian Academy of "
    "Sciences, Brown University and other European and North American institutes/companies), which were carried free of"
    " cost. Chandrayaan-1 became the first lunar mission to discover existence of water on the Moon. "
    "The Chandrayaan-1 team was awarded the American Institute of Aeronautics and Astronautics SPACE 2009 award, "
    "the International Lunar Exploration Working Group's International Co-operation award in 2008, and the National "
    "Space Society's 2009 Space Pioneer Award in the science and engineering category."
    "\n"
    "\n"
    "Chandrayaan-2"
    "\n"
    "Chandrayaan-2 is the second mission to the Moon, which included an orbiter, a lander and a rover. Chandrayaan-2 "
    "was launched on a Geosynchronous Satellite Launch Vehicle Mark III (GSLV-MkIII) on 22 July 2019, consisted of a "
    "lunar orbiter, the Vikram lander, and the Pragyan lunar rover, all of which were developed in India. It was the"
    " first mission meant to explore the little-explored lunar south pole region. The main objective of the Chandrayaan-2"
    " mission is to demonstrate ISRO's ability to soft-land on the lunar surface and operate a robotic rover on the "
    "surface. Some of its scientific aims are to conduct studies of lunar topography, mineralogy, elemental abundance,"
    " the lunar exosphere, and signatures of hydroxyl and water ice."
    "\n"
    "\n"
    "Mars Orbiter Mission (MOM) or (Mangalyaan-1)"
    "\n"
    "The Mars Orbiter Mission (MOM), informally known as Mangalyaan, was launched into Earth orbit on 5 November 2013 by"
    " the Indian Space Research Organisation (ISRO) and has entered Mars orbit on 24 September 2014. India thus became"
    " the first country to enter Mars orbit on its first attempt. It was completed at a record low cost of 74 million"
    " dollars. MOM was placed into Mars orbit on 24 September 2014 at 8:23 am IST. The spacecraft had a launch mass"
    " of 1,337 kg (2,948 lb), with 15 kg (33 lb) of five scientific instruments as payload. The National Space Society"
    " awarded the Mars Orbiter Mission team the 2015 Space Pioneer Award in the science and engineering category.";

const desc7 = "Along with a number of communication and earth observation satellites in future, ISRO aims to send "
    "humans into space and later establish a space station to facilitate a few weeks long stay of astronauts. "
    "Agency aims to develop and operationalise more powerful and less pollutive rocket engines to eventually "
    "develop much heavier rockets, develop electric and nuclear propulsion for satellites and spacecrafts for "
    "reduced weight and longer lives, landing a rover on the moon, sending missions to Sun, Venus, Mars, asteroids, "
    "comets and outer solar system, deploying more telescopes in space and developing satellite navigation systems "
    "with global coverage. Long-term plans may include manned landings on moon and other planets as well.";