const desc1 = "Modern space research in India is traced to the 1920s, when scientist "
    "S. K. Mitra conducted a series of experiments leading to the sounding of the ionosphere "
    "by applying ground-based radio methods in Kolkata. Later, Indian scientists like "
    "C.V. Raman and Meghnad Saha contributed to scientific principles applicable in space sciences. "
    "However, it was the period after 1945 that saw important developments being made in coordinated space research in India. "
    "Organised space research in India was spearheaded by two scientists: Vikram Sarabhai—founder of the "
    "Physical Research Laboratory at Ahmedabad—and Homi Bhabha, who established the Tata Institute of "
    "Fundamental Research in 1945. Initial experiments in space sciences included the study of cosmic radiation, "
    "high altitude and airborne testing, deep underground experimentation at the Kolar mines—one of the deepest "
    "mining sites in the world—and studies of the upper atmosphere. Studies were carried out at research laboratories, "
    "universities, and independent locations."
    "\n"
    "\n"
    "In 1950, the Department of Atomic Energy was founded with Bhabha as its secretary. The department provided "
    "funding for space research throughout India. During this time, tests continued on aspects of meteorology and "
    "the Earth's magnetic field, a topic that was being studied in India since the establishment of the observatory at "
    "Colaba in 1823. In 1954, the Uttar Pradesh state observatory was established at the foothills of the Himalayas."
    " The Rangpur Observatory was set up in 1957 at Osmania University, Hyderabad. Space research was further encouraged "
    "by the government of India. In 1957, the Soviet Union launched Sputnik 1 and opened up possibilities for the rest of "
    "the world to conduct a space launch"
    "\n"
    "\n"
    "The Indian National Committee for Space Research (INCOSPAR) was set up in 1962 by PM Nehru on the urging of "
    "Vikram Sarabhai. There was no dedicated ministry for space program initially and all activities of INCOSPAR "
    "relating to space technology continued to function within DAE. H.G.S. Murthy was appointed as the first Director "
    "of Thumba Equatorial Rocket Launching Station. Sounding rockets from Thumba Equatorial Rocket Launching Station "
    "were fired marking the start of upper atmospheric research in India. Indigenous series of sounding rockets named "
    "Rohini was subsequently developed and started undergoing launches from 1967 onwards.";

const desc2 = "Since the launch of Aryabhata in 1975, a number of satellite series and constellations have been "
    "deployed by Indian and foreign launchers. At present, ISRO operates one of the largest constellations of active "
    "communication and earth imaging satellites for military and civilian uses."
    "\n"
    "\n"
    "The IRS series"
    "\n"
    "The Indian Remote Sensing satellites (IRS) are the series of India's earth observation satellites. "
    "The IRS series provides remote sensing services and is the largest collection of remote sensing satellites for "
    "civilian use in operation today in the world. All the satellites are placed in polar Sun-synchronous orbit "
    "(except GISATs) and provide data in a variety of spatial, spectral and temporal resolutions to enable several "
    "programmes to be undertaken relevant to national development. The initial versions are composed of the 1 (A, B, C, D)"
    " nomenclature while the later versions were divided into sub-classes named based on their functioning and uses "
    "including Oceansat, Cartosat, HySIS, EMISAT and ResourceSat etc.. The names although again were unified into prefix "
    "EOS again regardless of functioning again in 2020. These satellites hold a wide range of applications including "
    "optical, radar and electronic reconnaissance for Indian agencies, city planning, oceanography and environmental studies."
    "\n"
    "\n"
    "The INSAT series"
    "\n"
    "The Indian National Satellite System (INSAT) are the family of communication satellites of India. "
    "It is a series of multipurpose geostationary satellites built and launched by ISRO to satisfy the telecommunications,"
    " broadcasting, meteorology and search-and-rescue needs of the country. Since the introduction of first satellite in"
    " 1983, INSAT has become the largest domestic communication system in the Asia-Pacific Region. It is a joint venture"
    " of the Department of Space, Department of Telecommunications, India Meteorological Department, "
    "All India Radio and Doordarshan. The overall coordination and management of INSAT system rests with the "
    "Secretary-level INSAT Coordination Committee. The nomenclature of satellite series was shifted to "
    "GSAT from INSAT which was further changed to CMS from 2020 onwards. These satellites have been in use by "
    "Indian Armed Forcesas well. GSAT-9 or SAARC Satellite is a notable example for serving communication services "
    "for India's smaller neighbors."
    "\n"
    "\n"
    "NavIC"
    "\n"
    "IRNSS with an operational name NavIC is an independent regional navigation satellite system developed by India. "
    "It is designed to provide accurate position information service to users in India as well as the region extending "
    "up to 1500 km from its borders, which is its primary service area. IRNSS provides two types of services, namely, "
    "Standard Positioning Service (SPS) and Restricted Service (RS) and provides a position accuracy of better than "
    "20 m in the primary service area. It is an autonomous regional satellite navigation system developed by "
    "Indian Space Research Organisation, which is under total control of Indian government. The requirement of such "
    "a navigation system is driven by the fact that access to global navigation systems like GPS is not guaranteed in "
    "hostile situations."
    "\n"
    "\n"
    "Other satellites"
    "\n"
    "Kalpana-1 (MetSat-1) was ISRO's first dedicated meteorological satellite. Indo-French satellite SARAL on "
    "25 February 2013. SARAL (or Satellite with ARgos and AltiKa) is a cooperative altimetry technology mission, "
    "used for monitoring the oceans' surface and sea levels. AltiKa measures ocean surface topography with an "
    "accuracy of 8 mm, against 2.5 cm on average using altimeters, and with a spatial resolution of 2 km.";

const desc3 = "";

const desc4 = "";

const desc5 = "";

const desc6 = "";

const desc7 = "";